[fz_vehicle]
friction = 1.25
mass = 1500.0
max_gyro_torque = 300
airbrake_duration = 0.3
stabilizer_fins_duration = 0.3
drag_coefficient_x = 0.47
drag_coefficient_y = 0.29
drag_coefficient_z = 1
drag_area_x = 3
drag_area_y = 2
drag_area_z = 13
airbrake_area_x = 40
airbrake_area_y = 20
airbrake_area_z = 0
stabilizer_fins_area_x = 40
stabilizer_fins_area_y = 0
stabilizer_fins_area_z = 0

["fz_repulsor:0"]
strafe_x = 0.0
turn_right_y = 60.0
turn_left_x = 60.0
activation_distance = 8.0
hover_y = 60.0
hover_x = 60.0
accelerate_x = 60.0
turn_right_x = 0.0
accelerate_y = 0.0
turn_left_y = 0.0
strafe_y = 60.0
force = 15000.0
repulsor_turning_angle = 540

["fz_repulsor:1"]
strafe_x = 0.0
turn_right_y = 0.0
turn_left_x = 0.0
activation_distance = 8.0
hover_y = -60.0
hover_x = 60.0
accelerate_x = 60.0
turn_right_x = 60.0
accelerate_y = 0.0
turn_left_y = -60.0
strafe_y = 60.0
force = 15000.0
repulsor_turning_angle = 540

["fz_repulsor:2"]
strafe_x = 0.0
turn_right_y = 0.0
turn_left_x = 0.0
activation_distance = 8.0
hover_y = 60.0
hover_x = -60.0
accelerate_x = 60.0
turn_right_x = -60.0
accelerate_y = 0.0
turn_left_y = 60.0
strafe_y = 60.0
force = 15000.0
repulsor_turning_angle = 540

["fz_repulsor:3"]
strafe_x = 0.0
turn_right_y = -60.0
turn_left_x = -60.0
activation_distance = 8.0
hover_y = -60.0
hover_x = -60.0
accelerate_x = 60.0
turn_right_x = 0.0
accelerate_y = 0.0
turn_left_y = 0.0
strafe_y = 60.0
force = 15000.0
repulsor_turning_angle = 540

["fz_thruster:0"]
force = 20000.0
