[fz_vehicle]
friction = 1.25
mass = 1900.0
max_gyro_torque = 8000
airbrake_duration = 0.2
stabilizer_fins_duration = 0.2
drag_coefficient_x = 0.8
drag_coefficient_y = 0.8
drag_coefficient_z = 1
drag_area_x = 9.06
drag_area_y = 2.61
drag_area_z = 11.25
airbrake_area_x = 0
airbrake_area_y = 0
airbrake_area_z = 0
stabilizer_fins_area_x = 0
stabilizer_fins_area_y = 0
stabilizer_fins_area_z = 0

["fz_repulsor:0"]
turn_right_y = 30.0
turn_left_x = 30.0
repulsor_turning_angle = 180
hover_x = 30.0
strafe_y = 45.0
accelerate_y = 0.0
turn_left_y = 0.0
turn_right_x = 0.0
strafe_x = 0.0
hover_y = 30.0
accelerate_x = 45.0
activation_distance = 1.5
force = 12000.0

["fz_repulsor:1"]
turn_right_y = 0.0
turn_left_x = 0.0
repulsor_turning_angle = 180
hover_x = 30.0
strafe_y = 45.0
accelerate_y = 0.0
turn_left_y = -30.0
turn_right_x = 30.0
strafe_x = 0.0
hover_y = -30.0
accelerate_x = 45.0
activation_distance = 1.5
force = 12000.0

["fz_repulsor:2"]
turn_right_y = 0.0
turn_left_x = 0.0
repulsor_turning_angle = 180
hover_x = -30.0
strafe_y = 45.0
accelerate_y = 0.0
turn_left_y = 30.0
turn_right_x = -30.0
strafe_x = 0.0
hover_y = 30.0
accelerate_x = 45.0
activation_distance = 1.5
force = 12000.0

["fz_repulsor:3"]
turn_right_y = -30.0
turn_left_x = -30.0
repulsor_turning_angle = 180
hover_x = -30.0
strafe_y = 45.0
accelerate_y = 0.0
turn_left_y = 0.0
turn_right_x = 0.0
strafe_x = 0.0
hover_y = -30.0
accelerate_x = 45.0
activation_distance = 1.5
force = 12000.0

["fz_thruster:0"]
force = 0.0
heating = 0.0
cooling = 0.0
ramp_time = 1.0

["fz_thruster:1"]
force = 0.0
heating = 0.0
cooling = 0.0
ramp_time = 1.0
